import Head from 'next/head';
import NavBar from './navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Javier Phon Zhee Kai </title>
        <meta name='description' content='Generated by me' />
        <link rel='icon' href='/favicon.ico'/>
      </Head>
    <main className='bg-white px-10'>
      <NavBar />
    </main>
    </div>
  )
}
